version: 2
jobs:
  build:
    docker:
      - image: debian:stretch 
    environment:
      MAKEFLAGS: "-i"
    branches:
      only:
        - master
    steps:
      - run: make
      - run: make install
